services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TalanHdf\NodeLinkVisualizer\:
    resource: '../Classes/*'

  TalanHdf\NodeLinkVisualizer\Controller\NodeLinkVisualizerController:
    public: true
    tags: ['controller.service_controller']