services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TalanHdf\NodeLinkVisualizer\:
    resource: '../Classes/*'

  TalanHdf\NodeLinkVisualizer\Controller\NodeLinkVisualizerController:
    public: true
    arguments:
      $connectionPool: '@TYPO3\CMS\Core\Database\ConnectionPool'